apiVersion: v1
kind: ServiceAccount
metadata:
  name: healthcare-app-sa
  namespace: healthcare-platform
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: healthcare-platform
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods-binding
  namespace: healthcare-platform
subjects:
  - kind: ServiceAccount
    name: healthcare-app-sa
    namespace: healthcare-platform
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
